# src/main/resources/application.yml
spring:
  application:
    name: CocinaDeLicia
  profiles:
    # local: local
    # dev: dev
    # prod: prod
    default: local

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

cognito:
  # valor por defecto, lo sobreescriben los profiles
  domain: ${COGNITO_DOMAIN:cdd-auth.auth.us-east-1.amazoncognito.com}

springdoc:
  swagger-ui:
    urlsPrimaryName: public