# src/main/resources/application-test.yml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # IMPORTANTe para tests: evitar llamadas externas y placeholders
          jwk-set-uri: http://localhost:0/fake-jwks # no se consulta hasta que se "decode"
app:
  cdn:
    base-url: http://localhost:0/fake-cdn-url-for-tests